# .github/workflows/deploy.yml

name: Fly Deploy

on:
  push:
    branches:
      - main  # Sugestão: usar 'main' como branch principal

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar o uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar dependências com uv
        # 'uv sync' é suficiente aqui, pois ele já instala no ambiente ativo.
        run: uv sync

      - name: Executar testes com pytest
        # 'uv run' é perfeito aqui para garantir que o pytest do venv seja usado.
        run: uv run pytest

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: test             
    concurrency: 
      group: deploy-group # Garante que apenas um deploy ocorra por vez
      cancel-in-progress: true # Cancela deploys antigos se um novo push for feito
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy para Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

